mkt/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from django.conf.urls.static import static
from django.views.generic import TemplateView
from wagtail.contrib.sitemaps.views import sitemap

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path('search/', include('search.urls')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    # Monitoring URLs
    path("monitoring/", include("monitoring.urls", namespace="monitoring")),
    path('communication/', include('communication.urls')),
    path('api/v1/blog/', include('blog.api_urls')),
    path('api/v1/monitoring/', include('monitoring.api_urls')),
    path('api/v1/communication/', include('communication.api_urls')), 
    # Prometheus metrics
    path('', include('django_prometheus.urls')),
    
    # Sitemap
    path('sitemap.xml', sitemap, name='sitemap'),
    
    # Documentation
    path('docs/', TemplateView.as_view(
        template_name='docs/index.html'
    ), name='documentation'),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search, name='search'),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse
from wagtail.models import Page
from django.shortcuts import render
try:
    from wagtail.search.models import Query as SearchQuery
except ImportError:
    try:
        from wagtail.search.query import Query as SearchQuery
    except ImportError:
        # Fallback for newer Wagtail versions
        Query = None
# To enable logging of search queries for use with the "Promoted search results" module
# <https://docs.wagtail.org/en/stable/reference/contrib/searchpromotions.html>
# uncomment the following line and the lines indicated in the search function
# (after adding wagtail.contrib.search_promotions to INSTALLED_APPS):

# from wagtail.contrib.search_promotions.models import Query


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)

        # To log this query for use with the "Promoted search results" module:

        # Only record query if Query model is available
        if Query:
            try:
                query = Query.get(search_query)
                query.add_hit()
            except:
                pass  # Ignore if query recording fails
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return render(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% if search_query %} for "{{ search_query }}"{% endif %} - {{ block.super }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 mx-auto">
        <h1>Search</h1>
        
        <form method="get" action="{% url 'search:search' %}">
            <div class="input-group mb-4">
                <input type="text" class="form-control" name="query" value="{{ search_query }}" placeholder="Search...">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>

        {% if search_query %}
            <h2>Results for "{{ search_query }}"</h2>
            
            {% if search_results %}
                {% for result in search_results %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% pageurl result %}">{{ result.title }}</a>
                            </h5>
                            {% if result.search_description %}
                                <p class="card-text">{{ result.search_description }}</p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}

                {% if search_results.has_other_pages %}
                    <nav aria-label="Search results pagination">
                        <ul class="pagination">
                            {% if search_results.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?query={{ search_query }}&page={{ search_results.previous_page_number }}">Previous</a>
                                </li>
                            {% endif %}
                            
                            <li class="page-item active">
                                <span class="page-link">{{ search_results.number }} of {{ search_results.paginator.num_pages }}</span>
                            </li>
                            
                            {% if search_results.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?query={{ search_query }}&page={{ search_results.next_page_number }}">Next</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            {% else %}
                <p>No results found.</p>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}